### ISSUE TITLE
Solutions 1 through 10 missing

### ISSUE THREAD

**Issue by bscan** [jaebradley/project_euler#1]
Where'd ya put 'em?

**Comment by jaebradley** [comment]
if you can't solve the first ten, just don't bother with the next 40

**Comment by bscan** [comment]
Fair enough.

**Comment by jaebradley** [comment]
ANYBODY READING THIS WE KNOW EACH OTHER THIS IS JUST FRIENDLY BANTER AMONGST COLLEAGUES
